### ISSUE TITLE
Апстрим Jade ебанулся

### ISSUE THREAD

**Issue by m1kc** [uonline/uonline#346]
В новой версии не работают условные комментарии.

**Comment by vkomodey** [comment]
ты лучший

**Comment by euqen** [comment]
++++

**Comment by m1kc** [comment]
И вам доброго дня, благородные сэры 🦊
А вы откуда?

**Comment by pttsky** [comment]
Сейчас был в репозитории pugjs, мягко говоря был обескуражен, наткнувшись на русскую речь 
 в названии referenced issue посреди обсуждения. Спасибо, поржал.
