### ISSUE TITLE
Энергия - полоска

### ISSUE THREAD

**Issue by m1kc** [uonline/uonline#468]
То есть она должна встать в один ряд со здоровьем и маной, поле energy должно стать energy_max, а просто energy показывать её текущее значение.

P.S. Атрибуты aria- обязательны для полосок, даже если без них всё выглядит точно так же.

**Comment by 3bl3gamer** [comment]
energy_max есть, в профиле полоска слева есть, во время боя полоски нет.

**Comment by m1kc** [comment]
Ты бы согласовал цифры с Саньком сначала. Сейчас там что?

/cc @FaceLess1

**Comment by FaceLess1** [comment]
итак, внимание.
по энергии среди рас ситуация такая:
орк мужчина -- 220
орк женщина --200
эльф мужчина -- 150
эльф женщина -- 140
хуман мужчина -- 170
хуман женщина -- 160

это данные на 1-й лвл для рас.
каждый уровень автоматически "+10", а за распределенное на этот стат очко уровня (условно назовем так) -- еще по "+5" за каждое.

**Comment by 3bl3gamer** [comment]
Цифра там была '100' где-то выше в миграциях, оттуда и взял.

И вообще, мб лучше хранить все эти значения по умолчанию в какой-нибудь таблице типа `stats_config`? А то они сейчас по всем миграциям размазаны.
