### ISSUE TITLE
Окно экипировки / Инвентарь

### ISSUE THREAD

**Issue by FaceLess1** [uonline/uonline#475]
человеки, я же просил окно экипировки. это первое.
второе: у вас нет вещей? как нет? щит есть, шлем есть, оружие есть, сапоги есть. вот возьмите по своему вкусу оружие, захватите щит, сапоги и шлем, я присвою им тестовые характеристики и внесите на сервер.

**ЗАДАЧА**: наполните инвентарь. хочу увидеть шмотки. от этого зависит следующая задача.

П.С. а почему в "Экипировка" есть наручи (которые, кстати, не рисовал), но нет щита и оружия? связано с тем, что я не перечислял ранее?

**Comment by m1kc** [comment]
https://m1kc-dev-uo.herokuapp.com/

Как-то так. Всё есть, всё должно работать (но тесты писал Антон, так что я не полностью уверен). Доспехи учитываются и ломаются, и их можно снимать и надевать. Играйся. В бою надевать тоже не запрещено.

![2015-01-02 04 19 50](https://cloud.githubusercontent.com/assets/1831620/5593743/a48ef384-9236-11e4-97f8-081f3bfbc68c.png)

Карточку закрываем?

**Comment by FaceLess1** [comment]
прошу прощения за задержку. вопросы: 
1) какие еще вещи можно кинуть для разнообразия?
2) я предполагаю, что нужно что-то еще придумать с оружием. это можно?
3) можно будет позже пофиксить, чтобы в бою не было возможности одевать/снимать одежду? про оружие я вот пока не определился, но аргументацию с вещами я уже писал: "погоди, не бей, ща вот наплечник сменю".

**Comment by m1kc** [comment]
1. Да любые шмотки.
2. &darr;
3. Угу.

С оружием, щитами и прочим мы пока ничего не придумали. Вообще, можешь составить список, какие типы вещей у нас будут и какие у них характеристики могут быть? И что у нас дальше по плану?

**Comment by FaceLess1** [comment]
1. ну, полагаю, что пока я не нарисую новые -- особо смысла их кидать нет.
2. вот с оружием и щитами надо теперь сделать такое же, как с броней.
щиты я умышленно выделил в особую категорию, так как будут специальные "малые щиты", у которых **процент закрытия фигуры** персонажа хоть и небольшой, но ими можно наносить повреждения. такие повреждения небольшие, но выше, чем просто бить безоружной рукой. 

**процент закрытия фигуры** -- на деле это просто вероятность, что урон влетит именно в щит, а не по персонажу. 
могут возникнуть вопросы по поводу: "а ведь у нас есть вероятность попадания, не конфликтует ли новый параметр с этим обстоятельством?". ответ: нет, не конфликтует. поскольку после того, как алгоритм рассчитает, что по игроку попаданию все же быть, то она теперь рассчитывает а попадет ли урон по игроку или по щиту. для формулы это просто еще один коэффициент вероятности попадания и неплохой способ для выживания. 
обязательные параметры любого щита: "процент закрытия фигуры" и "прочность". "прочность" -- это своего рода "здоровье щита". предугадываю вопрос о распределении урона, когда у щита осталось ничтожный запас прочности, а нанесенный урон значительно выше. ответ: урон поглощается в таком случае полностью и не распространяется ни на здоровье персонажа, ни на его экипировку. щит ломается. 

так что давайте с щитами разберемся.
что мне для этого нужно сделать? что пояснить, расписать, подсчитать?

**Comment by m1kc** [comment]
Я бы хотел сначала со структурой инвентаря определиться - по крайней мере с тем, что по-любому будет. Сейчас представляю что-то такое:

- Броня
  - Название
  - Процент покрытия
  - Прочность (максимальная и текущая)
  - Плюс к силе, защите, ловкости, точности, инициативе и энергии
- Оружие
  - Название
  - Тип (одноручное/двуручное)
  - Плюс к дамагу
  - Плюс к силе, защите, ловкости, точности, инициативе и энергии
- Щиты
  - Название
  - Процент покрытия
  - Прочность (максимальная и текущая)
  - Дамаг при ударе (если 0, этим щитом бить нельзя)
  - Плюс к силе, защите, ловкости, точности, инициативе и энергии
- Безделушки, ингредиенты
  - Название
- Зелья
  - Название
  - Восстановление здоровья, маны (мгновенно)
  - Бонус к силе, защите, ловкости, точности, инициативе и энергии
  - Время действия этого бонуса

----------

```
- Броня
  - Название
  - Процент покрытия
  - Прочность (максимальная и текущая)
  - Плюс к силе, защите, ловкости, точности, инициативе и энергии
- Оружие
  - Название
  - Тип (одноручное/двуручное)
  - Плюс к дамагу
  - Плюс к силе, защите, ловкости, точности, инициативе и энергии
- Щиты
  - Название
  - Процент покрытия
  - Прочность (максимальная и текущая)
  - Дамаг при ударе (если 0, этим щитом бить нельзя)
  - Плюс к силе, защите, ловкости, точности, инициативе и энергии
- Безделушки, ингредиенты
  - Название
- Зелья
  - Название
  - Восстановление здоровья, маны (мгновенно)
  - Бонус к силе, защите, ловкости, точности, инициативе и энергии
  - Время действия этого бонуса

**Comment by m1kc** [comment]
\>> #494
