### ISSUE TITLE
Щиты/Инвентарь

### ISSUE THREAD

**Issue by FaceLess1** [uonline/uonline#493]
значит, нам необходимо ввести щиты. 
что я, собственно, хочу. то же самое, что и с броней (#475) -- такой тип вещей нужно уметь помещать в инвентарь и экипировать его. 

существуют большие, средние и малые щиты. 
общими параметрами являются:
1. процент закрытия фигуры
2. прочность. 
для малых процент закрытия фигуры в диапазоне 13-25%, для средних в диапазоне 29-45%, для больших в диапазоне 65-90%.
параметр прочности зависит от размера щита (процент закрытия фигуры) материала изготовления и качества изделия (кроме легендарных и редких вещей). 
для малых щитов к двум указанным параметрам добавляется параметр "Урон". "Урон" обозначается диапазоном чисел и таким образом малый щит является некой альтернативой оружию.

пока что я не определился с вот такими вещами (от общего к частному):
1. по одной из моих мыслей, я хочу всем предметам присвоить объем и вес дополнительно к их параметрам. является ли невозможность сделать это сейчас проблемой? потому что я пока что не готов дать ответ. но пока у нас инвентарь безразмерный, а персонаж поднимет даже тонну вещей, я пока даже не знаю как.
2. стоит ли параметр прочности и без того непрочного (относительно других) малого щита ослаблять нанесением им ударов? вроде как вещица должна потихоньку изнашиваться в процессе и в конце концов ломаться.

**Comment by FaceLess1** [comment]
![image](https://cloud.githubusercontent.com/assets/4042329/5670804/481d5060-9794-11e4-9094-b9df59b93999.png)
можно оставить это здесь? наглядное изображение малых щитов. меня не покидало ощущение, что где-то я их уже видел, однако никак не мог найти где. потому поначалу авторство приписал себе. однако только что нашел вот это -- это они и есть. точнее, саму идею я взял не отсюда, но то, что я не сбрендил -- тому реальное подтверждение.

**Comment by m1kc** [comment]
\>> #536
