### ISSUE TITLE
Генераторы

### ISSUE THREAD

**Issue by m1kc** [uonline/uonline#495]
Может быть, это хорошая идея, может, плохая. В любом случае пусть карточка повисит.

**Comment by m1kc** [comment]
https://github.com/spion/genny

**Comment by m1kc** [comment]
- [x] CoffeeScript [поддерживает](http://coffeescript.org/#1.9.0) генераторы с версии 1.9.0.
- [x] io.js поддерживает генераторы с версии 1.0.0.
- [x] Travis CI [поддерживает](http://docs.travis-ci.com/user/build-environment-updates/2015-02-03/#io.js-support) io.js
- [x] Heroku [поддерживает](https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version) io.js

Охуеть, все поддерживают. Когда составлял это список - думал, что как минимум Heroku прослоупочит. Но нет. Видимо, нода всех уже достала.

**Comment by m1kc** [comment]
- [ ] io.js не поддерживается sync и маинтайнер - ленивая скотина, так что придётся выбирать одно из двух.

**Comment by 3bl3gamer** [comment]
У sync'а есть минимум 2 преимущества:
1) не нужно всё переписывать
2) не нужно каждый чик оборачивать в особую функцию

**Comment by m1kc** [comment]
Со вторым я бы поспорил. Сколько у нас сейчас этих `f = (bla->blabla).async()`?

**Comment by 3bl3gamer** [comment]
Да. Но если их выпилить, а все функции вызывать как синхронные...

**Comment by m1kc** [comment]
...то нам всё равно всё переписывать. Кроме того, эти функции всё равно будут ждать, что наверху там кто-то обернул всё это в sync(), и это по-прежнему нужно будет делать для каждой мидлвари (потому что express иначе не умеет).

Ну и вообще:

1. Чота мне начало казаться, что io.js резко вошёл в тренд и от ноды скоро начнут отказываться.
2. Генераторы умеют в параллельное исполнение, а я знаю десяток мест, где оно бы пригодилось.
3. Они не требуют дополнительной библиотеки, маинтайнер которой - ленивая скотина, которая сначала месяц не отвечает на PR, а потом его саркастически заворачивает.
4. Эти их thunks позволяют вообще ничего не таскать, кроме обёртки сверху. Просто пишешь fs.readFile('file') и готово.

**Comment by m1kc** [comment]
- [ ] uglify-js 2.4.16 не умеет разбирать код со словом yield. Хы-хы.

**Comment by m1kc** [comment]
https://www.npmjs.com/package/funkify

**Comment by m1kc** [comment]
#616
