### ISSUE TITLE
Инвентарь

### ISSUE THREAD

**Issue by m1kc** [uonline/uonline#496]
@FaceLess1, попробуем ещё раз. #494 - это очень клёво, но мне в данный момент нужно другое: определиться, какие _в принципе_ характеристики могут быть у предметов. Могут ли кольца давать плюс к инициативе? Могут ли зелья восстанавливать энергию? Какие предметы могут считаться квестовыми - все? Короче, я хочу, чтобы ты взял этот список, исправил и дополнил его. Сделаешь?

----------------------

```
- Броня
  - Название
  - Процент покрытия
  - Прочность (максимальная и текущая)
  - Плюс к силе, защите, ловкости, точности, инициативе и энергии
- Оружие
  - Название
  - Тип (одноручное/двуручное)
  - Плюс к дамагу
  - Плюс к силе, защите, ловкости, точности, инициативе и энергии
- Щиты
  - Название
  - Процент покрытия
  - Прочность (максимальная и текущая)
  - Дамаг при ударе (если 0, этим щитом бить нельзя)
  - Плюс к силе, защите, ловкости, точности, инициативе и энергии
- Безделушки, ингредиенты
  - Название
- Зелья
  - Название
  - Восстановление здоровья, маны (мгновенно)
  - Бонус к силе, защите, ловкости, точности, инициативе и энергии
  - Время действия этого бонуса

**Comment by FaceLess1** [comment]
а, тю, я тогда тебя неверно понял. ок. по порядку:
1. все вот это вот у тебя в порядке. по крайней мере, если я все правильно понимаю.
2. кольца, амулеты и перстни могут давать плюс к чему угодно. а в некоторых случаях давать и минус. какое-нибудь "кольцо безумия" даст +100 к мане и -10 к интеллекту -- ну вот так примерно. а "амулет инициативы" может запросто повышать инициативу. 
3. зелья могут восстанавливать что угодно -- зависит от зелья. уже имеется 4 гриба. добавятся еще минимум 4, потом добавятся иные предметы (чеснок, например, и травы) -- короче, получится такой спектр возможных комбинаций, что зелья, эссенции, тоники и прочее смогут восстановить что угодно. 
4. время действия -- это могут быть как зелья мгновенного восстановления, так и восстанавливать в течении времени. 
5. о квестовых предметах: как правило, это ОТДЕЛЬНЫЕ предметы, которые помещаются в ОБЩИЙ инвентарь, занимая там место. что-то вроде защиты от дебилов, любящих брать 100500 квестов. то есть это наподобие "Старинного серебряного ключа" или "Потерянная ваза". но я не исключаю случая, если вруг квестодатель попросит принести ему ягод/грибов, которые персонаж может употребить и сам. у персонажа эти вещи могу оказаться в инвентаре, что позволит исполнить квестовое задание практически мгновенно. в общем, это зависит от того, кто будет писать квесты. а главное -- какие будут написаны квесты. я ведь предлагал отправить персонажа на поле сражения за мечами -- я не вижу ничего мешающего захватить с поля не 3 (как просили), а 4 меча -- четвертый экипировать.

**Comment by FaceLess1** [comment]
к **Броне** стоит добавить, возможно, "Материал" (не всегда из названия ясно) и, думаю, потребуется к некоторым вещам добавить "Ценз экипировки". я писал ранее "ценз ношения", что не совсем корректно: "ношение" -- это не только ношение на себе, но и в инвентаре, а вот "экипировка" -- это конкретно на себе, помещение в инвентарь не в счет. отдельные экземпляры могут завать плюсы/минусы к характеристикам персонажа (особенно легендарные).

к **Оружие** и **Щит** -- см. **Броня**

по т.н. "Безделушкам" (я полагаю, что это бижутерия и ювелирка вроде амулетов, колец и перстней): необходимо добавить "Материал" и прирост/убыль по характеристикам персонажа.

по прочим предметам и ингридиентам -- зависит от предмета. условно разделим на "квестовые" и "неквестовые" (помня, что иногда неквестовые могут стать квестовыми, а квестовые возможно употребить в виде неквестовых, забив на квест). квестовые, я так понимаю, должны иметь название (тут все правильно) и, наверное, подсказку о том, для какого квеста он (предмет этот) нужен (хотя тут я сомневаюсь). неквестовые -- нужно добавить, я полагаю, оказываемый эффект предметом, если нет желания реализовывать это на страницах Дневника (Журнала, Блокнота или что там будет у персонажа).

по зельям -- нужно название, оказываемый эффект и указание времени действия, где точное число с указанием системы исчисления (секунды, минуты, часы, дни) показывает время продолжительного действия, а отсутствие такового указывает, что эффект приходит мгновенно. условное "Зелье здоровья" может восстановить сразу, скажем, 200 здоровья, а условное "Зелье регенерации" позволяет восстанавливать по 10 единиц здоровья в секунду и длиться половину минуты. кроме тоо можно это самое "Зелье регенерации "баффнуть еще сильнее и позволить при его потреблении превысить временно максимум здоровья на, скажем, 25% (т.н. "сверхвосстановление") на ограниченное время (на время действия этого зелья).

**Comment by m1kc** [comment]
Ну сделай ты готовый список, не мучай меня. А то окажется потом, что одно поле забыли.

**Comment by FaceLess1** [comment]
- Броня
  - Название
  - Процент покрытия
  - Прочность (максимальная и текущая)
  - Материал
  - Плюс к силе, защите, ловкости, точности, инициативе и энергии
  - Ценз экипировки
- Оружие
  - Название
  - Тип (одноручное/двуручное)
  - Плюс к дамагу
  - Материал
  - Плюс к силе, защите, ловкости, точности, инициативе и энергии
  - Ценз экипировки
- Щиты
  - Название
  - Процент покрытия
  - Прочность (максимальная и текущая)
  - Материал
  - Дамаг при ударе (если 0, этим щитом бить нельзя)
  - Плюс к силе, защите, ловкости, точности, инициативе и энергии
  - Ценз экипировки
- Безделушки (кольца, перстни, амулеты)
  - Название
  - Материал
  - Плюс к силе, защите, ловкости, точности, инициативе и энергии
  - Ценз экипировки
- Ингредиенты и прочие предметы
  - Название
  - Описание
  - Оказываемый эффект
- Зелья
  - Название
  - Оказываемый эффект (бонус к характеристикам, восстановление здоровья, маны, энергии)
  - Время действия этого бонуса

**Comment by m1kc** [comment]
1. Материал - это что? Просто текст? Или вещь можно будет переплавить, чтобы этот материал получить?
2. Ценз экипировки - он какие конкретно статы может включать?
3. Описание есть только у ингредиентов? Полагаю, что нет.
4. "Зелья - Оказываемый эффект (бонус к характеристикам" - какие именно характеристики могут бафаться?
5. Я так понял, зелья восстанавливают здоровье/ману/энергию сразу, а бонус к статам дают на время. Я прав?
6. "Ингредиенты и прочие предметы - Оказываемый эффект" - какой эффект они могут оказывать?
7. У тебя ещё в списке была еда. Её не будет?

**Comment by 3bl3gamer** [comment]
> восстанавливать по 10 единиц здоровья в секунду

А во время боя как это как будет работать? Если считать время в бою = реальному времени, ходы будут затягиваться, чтобы отрегенить побольше на следующий ход. (С временными бафами проще: там эффект обратный).

P.S.: я смутно припоминаю обсуждение чего-то подобного в одной из карточек. Этот вопрос уже был решён?

**Comment by FaceLess1** [comment]
решения вижу такие:
1. можно приравнять ход к уже условленному количеству времени (допустим, 3 секунды)
2. можно запретить такие лечилки в боях.
3. можно такие лечилки не создавать вообще. я не думаю, что мы в балансе игры или в геймплее что-то потеряем, я выдал просто вариант.
 
нет, конкретно этот вопрос, на моей памяти, нигде не обговаривался, я выдал просто вариант. поэтому можно обсудить.

**Comment by 3bl3gamer** [comment]
1. тогда наверно надо будет делать ещё минимальное время хода, а то быстрым боем без ударов можно будет ускорять действее эффектов.

Да, и кроме лечилок способстввать затягиванию ходов будут всякие дебафы типа "-5 силы на 30 секунд".

**Comment by FaceLess1** [comment]
вот серьезно, этот микс пошаговости и реального времени меня несколько смущает. ну и да, на "30 секунд" -- как-то маловато. уже минутами надо бы исчислять чтоли...

**Comment by m1kc** [comment]
Я бы, типа, разделил эффекты на боевые и небоевые. Боевые действуют по ходам и снимаются в конце боя. Небоевые - действуют по времени и только в мирное время.

@FaceLess1, всё ещё жду ответов.

**Comment by m1kc** [comment]
Поправка: у небоевых на время боя снимается всякий там реген, плюсы к статам остаются.

**Comment by FaceLess1** [comment]
1. насчет преобразования вещи в материал -- не знаю. вообще, на перспективу, было бы прикольно, но пока обойдемся. у нас ВООБЩЕ пока никак крафт не реализован, а обратный порядок -- пока жирновато.
2. ценз экипировки может включать в себя ограничения по силе, защите, ловкости, точности и интеллекту.
3. вообще я за описание только у ингредиентов. логики тут нет, знаю.
4. бафаться могут ВСЕ параметры (в том числе и личные, которые экипировкой не бафаются)
5. выше вроде как не определились: будут ли зелья уметь восстанавливать здоровье со временем (повышенная регенерация) или нет. пока что -- нет. то есть ты прав, да.
6-7. "прочие предметы" - в т.ч. и "еда". оказываемый эффект, пример: "Яблоко. восстанавливает 23 единицы здоровья" или "Гриб-решеточник. Отравляет на 5 минут, -5 здоровья каждые 10 секунд".

**Comment by m1kc** [comment]
Спасено из https://github.com/uonline/uonline/issues/536:

         | Броня | Оружие | Щиты | Безделушки | Ингредиенты и др. | Зелья
---------|-------|--------|------|------------|-------------------|-------
Название |  +    |  +     |  +   |  +         |  +                |  +
Описание |  +    |  +     |  +   |  +         |  +                |  +
Тип | + | + | + |  |  | 
Процент покрытия | + |  | + |  |  | 
Дамаг |  | + | + |  |  | 
Прочность (х2) | + |  | + |  |  | 
Материал | + | + | + |   |   |  
Плюс к статам | + | + | + | + | +* | +*
Ценз экипировки | + | + | + | + |  | 
Время действия бонуса |  |  |  |  |  | +
Вес | + | + | + | + | + | +
Объём | + | + | + | + | + | +

**Comment by m1kc** [comment]
Ушло сюда: :page_facing_up: [items.md](https://github.com/uonline/universe/blob/master/game-design/%D0%94%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82/items.md)
