### ISSUE TITLE
ВСЁ СЛОМАНО

### ISSUE THREAD

**Issue by m1kc** [uonline/uonline#498]
Антон, а ты пробовал вообще сервер запускать и страницы там всякие тыкать? Там сейчас _ничего_ не работает.

**Comment by 3bl3gamer** [comment]
Да.
И я сейчас понял, что забыл проверить, что будет после проведения миграций уже заполненной базы.

**Comment by m1kc** [comment]
Твои действия?

**Comment by 3bl3gamer** [comment]
Починить, учесть, запомнить.

**Comment by 3bl3gamer** [comment]
Починил, изменив последнюю миграцию. Закоммитил, могу пушнуть.

Или могу откатить этот коммит и добавить ещё одну миграцию, исправляющую ошибки предыдущей.

**Comment by m1kc** [comment]
Надо новую, ту я уже на dev выкатил.

**Comment by m1kc** [comment]
А выкати всё это на dev?

**Comment by m1kc** [comment]
Ну типа там `git push heroku master:master`, `heroku run bash`, `./init.coffee -m` и что ещё потребуется.

**Comment by 3bl3gamer** [comment]
Готово.
А куда оно пишет логи?

**Comment by m1kc** [comment]
```bash
heroku logs -t
