### ISSUE TITLE
Редизайн про персонажей

### ISSUE THREAD

**Issue by m1kc** [uonline/uonline#500]
- [x] Разделить профили персонажа и игрока
- [x] Переделать верхнюю панель
- [x] Разобраться с иконками
- [x] Сделать выпадайку
- [x] Сделать переключение персонажей
- [x] Сделать регистрацию без создания персонажа
- [x] Сделать создание персонажей
- [x] Сделать удаление персонажей
- [x] Научить игру правильно реагировать, если персонажей нет или ни один не выбран
- [x] Переделать профиль игрока

**Comment by m1kc** [comment]
- [ ] Разделить профили персонажа и игрока

**Comment by m1kc** [comment]
- [ ] Переделать верхнюю панель

**Comment by m1kc** [comment]
- [ ] Разобраться с иконками

**Comment by m1kc** [comment]
- [ ] Сделать переключение персонажей

**Comment by m1kc** [comment]
- [ ] Сделать регистрацию без создания персонажа
- [ ] Сделать создание персонажей
- [ ] Сделать удаление персонажей
- [ ] Научить игру правильно реагировать, если персонажей нет или ни один не выбран

**Comment by m1kc** [comment]
- [ ] Переделать профиль игрока

**Comment by 3bl3gamer** [comment]
Насчёт адресов. Я их по инерции называл через подчёркивание, и только потом заметил и вспомнил `isNickBusy` и т.д. Переименовать `new_character` аналогично?

Насчёт `func.async()`. Результат её можно вызывать как через sync `func.sync null, bla, bla`, так и без `func(bla, bla)`. Вроде это уже обсуждали. Но я не помню, что мы тогда решили насчёт пользования это фичей. Да/нет?

**Comment by m1kc** [comment]
> Переименовать?

Ну ясное дело.



> что мы тогда решили

Мы тогда ничего не решили, но если что - я против таких вещей и за совместимость со стандартным API.

**Comment by 3bl3gamer** [comment]
И ещё про адреса. Вот префикс `/action/...`, смысл его - какое-то действие, ок. Но регистрация, например, - тоже действие, а она работает POST'ом на `/register/`. Аналогично с `newCharacter`. Ну тут ещё ладно: `GET path` - получаем форму,  `POST path` - отправляем её обратно, логика есть. А теперь появляется `deleteCharacter`! Действие? Действие. Но в `/action/deleteCharacter` оно выглядит странно, потому что парная ему `newCharacter` запрашивается без префикса.
Ты какой смысле в `/action/` закладывал? Может не так понял/запомнил?

**Comment by 3bl3gamer** [comment]
> https://github.com/uonline/uonline/commit/95c10fd4f3b7d242ec56fd1ca30f50d9869c1548

Если удалить текущего персонажа, автопереключения на другого не будет. В `character_id` впишется `NULL`.

**Comment by 3bl3gamer** [comment]
А может... нафиг это удаление персонажей вообще? А если этот персонаж сейчас в бою? А если он засветился в таблице каких-нибудь рейтингов? Оставил предмет в какой-нибудь камере хранения? Находится с кем-то в группе/отряде? Это ж надо будет кучу всего за ним подчищать. Логи боёв тоже посмотреть нормально не получится.

**Comment by m1kc** [comment]
> И ещё про адреса. Вот префикс /action/..., смысл его - какое-то действие, ок. Но регистрация, например, - тоже действие, а она работает POST'ом на /register/. Аналогично с newCharacter. Ну тут ещё ладно: GET path - получаем форму, POST path - отправляем её обратно, логика есть. А теперь появляется deleteCharacter! Действие? Действие. Но в /action/deleteCharacter оно выглядит странно, потому что парная ему newCharacter запрашивается без префикса.
> Ты какой смысл в /action/ закладывал? Может не так понял/запомнил?

А как бы ты сделал?



> А может... нафиг это удаление персонажей вообще? А если этот персонаж сейчас в бою? А если он засветился в таблице каких-нибудь рейтингов? Оставил предмет в какой-нибудь камере хранения? Находится с кем-то в группе/отряде? Это ж надо будет кучу всего за ним подчищать. Логи боёв тоже посмотреть нормально не получится.

Всё зачищать. А ты как думал? В банке будут лежать бесхозные доспехи? В группе останется призрак?

В некоторых случаях надо будет зачищать не полностью, но это уже отдельные случаи, пока таких нет.

**Comment by 3bl3gamer** [comment]
> А как бы ты сделал?

Для дейтвий POST, для отображения GET. Как у регистрации. Только без костылей это нифига не заработает, потому что для того же удаления персонажа придётся `<a>` заменять на форму.

Если бы делал что-то мелокое для себя, попробовал бы вынести вообще все действия (ту же регистрацию) в `/action/` и не обращать внимания на метода запроса. Хотя такого я ещё нигде не встречал.

> В группе останется призрак?

Заменяем ему при удалении айдищник игрока на ИИ, пусть дальше сам бегает и качается ~~и мстит бывшему хозяину~~.
