### ISSUE TITLE
_Нормальное_ удаление персонажей

### ISSUE THREAD

**Issue by m1kc** [uonline/uonline#511]

**Comment by 3bl3gamer** [comment]
Всё, броня при удалении теперь испаряется. А ещё персонажа нельзя удалить во время боя (боя этого персонажа).

До "\_нормального\_", правда, всё равно не дотягивает, потому что и при неправльном юзере, и при активном бое результат будет один: `false`. А во втором случае пользователю надо бы намернуть, почему кнопка не сработала.

Поидее, надо сделать ещё один запрос, проверяющий, а не в бою ли персонаж, заблокировав предварительно ему вступление в бои. Как это через `SELECT ... FOR UPDATE` организовать, я не знаю (ну не всю же таблицу с боями лочить), а https://github.com/uonline/uonline/issues/459 пока нету.
