### ISSUE TITLE
Валидация имён персонажей

### ISSUE THREAD

**Issue by m1kc** [uonline/uonline#517]
Max Musatov, [20.04.15 18:45]
И валидация ещё, кстати.

Антон Гарифуллин, [20.04.15 18:51]
> валидация

А у персонажей тоже уникальные имена должны быть?

Max Musatov, [20.04.15 18:51]
Угу. И там ограничения на имя другие.

Max Musatov, [20.04.15 18:55]
Имя аккаунта - латиница, цифры, дефисы, подчёркивания.

Max Musatov, [20.04.15 18:56]
Имя персонажа - латиница или кириллица (что-нибудь одно), пробелы, дефисы.

Max Musatov, [20.04.15 18:57]
Плюс имя персонажа нельзя начинать со спецсимвола и нельзя ставить несколько оных подряд.

**Comment by 3bl3gamer** [comment]
TODO:
 * проверка занятости аяксом со страницы
 * проверка занятости при создании персонажа

**Comment by 3bl3gamer** [comment]
https://travis-ci.org/uonline/uonline/builds/60775281
Какого...

**Comment by 3bl3gamer** [comment]
```
detail: 'Key (name)=(My First Character) already exists.',
...
where: undefined,
schema: undefined,
table: undefined,
column: undefined,
dataType: undefined,
constraint: undefined,
```

Ну и как это понимать?

**Comment by 3bl3gamer** [comment]
Поставил себе ноду v0.10.38, всё ок.

**Comment by 3bl3gamer** [comment]
Бинго!

**Comment by 3bl3gamer** [comment]
Проверка валидности есть, аякс есть, проверка занятости тоже есть. Даже билд проходит.
