### ISSUE TITLE
lib/locparse.coffee: 298:22 Expected a conditional expression and instead saw an assignment.

### ISSUE THREAD

**Issue by m1kc** [uonline/uonline#524]

**Comment by 3bl3gamer** [comment]
Но оно так и задумано!

**Comment by m1kc** [comment]
Ну напиши как-нибудь по-другому.

**Comment by 3bl3gamer** [comment]
Ну... Эээ... Зато не ругается https://github.com/uonline/uonline/commit/839ac8422e0fdb5d0c97b995c1066e1a8944f202
