### ISSUE TITLE
Щиты

### ISSUE THREAD

**Issue by 3bl3gamer** [uonline/uonline#536]
## Характеристики
(https://github.com/uonline/uonline/issues/496#issuecomment-73362425)
* Название
* Процент покрытия
* Прочность (максимальная и текущая)
* Материал
* Дамаг при ударе (если 0, этим щитом бить нельзя)
* Плюс к силе, защите, ловкости, точности, инициативе и энергии
* Ценз экипировки

Тестовый экземпляр (https://github.com/uonline/uonline/issues/494#issuecomment-72916556)
* Название: Укрепленный деревянный щит
* Процент закрытия фигуры: 34%
* Прочность: 440
* Материал: Дерево и железо
* Дамаг при ударе: 0
* Прироста к параметрам персонажа не имеет
* Ценз ношения: нет

**Comment by 3bl3gamer** [comment]
## Как харнить
Мы тогда напридумывали два варианта:
1. по одной отдельной таблице для брони, оружия, зелий и т.д.
2. одну общую таблицу, в которой не все столбцы будут использоваться для всех вещей

Второй вариант вроде как получается лучше (меньше костылей, ифов и звпросов, а параметры у передметов более-менее похожи).

**Comment by 3bl3gamer** [comment]
> Короче, надо бы определиться со столбцами и запилить эту таблицу.
> Или можно просто переименовать armor в items, а остальное дописывать при случае.

...в процессе...

**Comment by 3bl3gamer** [comment]
## Броня сейчас
```
uonline=# \d armor
 id        | integer | not null default nextval('armor_id_seq'::regclass)
 prototype | integer | 
 owner     | integer | 
 strength  | integer | 
 equipped  | boolean | default true

uonline=# \d armor_prototypes
 id           | integer | not null default nextval('armor_prototypes_id_seq'::regclass)
 name         | text    | 
 type         | text    | 
 strength_max | integer | 
 coverage     | integer | 
```

**Comment by m1kc** [comment]
Ну, всё правильно. Описание есть у всех. Тип у щитов есть. Вообще, забей пока на всё, кроме щитов, и на дополнительные параметры тоже забей, они сейчас не важны. Сделай удары щитом и защиту щитом и будет ок.

**Comment by 3bl3gamer** [comment]
(думал пойти афк на 20 минут, получилось на 5 часов)

> Броня сейчас

Я там вот что предложить хотел: параметры из прототипов перенести в саму броню, и протипы не использовать. Т.е. сделать одну таблицу items без зависимостей. Потому что то же покрытие и максимальная прочночть могут поменяться после какой-нибудь модификации (в теории). С названием, правда, фигово получается (оно же точно меняться не сможет? хотя...).

**Comment by m1kc** [comment]
Ты сейчас предлагаешь добавить десять новых колонок, в которых будет храниться одно и то же. Зачем?

**Comment by 3bl3gamer** [comment]
Десять? Каких десять? Почему одно и то же? Их там 4, две из которых впринципе могут меняться.

А ты что предлагаешь делать с этими таблицами? Перименовать в `items` и `items_prototypes` и раскидывать параметры между ними по мере необходимости?

**Comment by m1kc** [comment]
> две из которых впринципе могут меняться

Какие?

> А ты что предлагаешь делать с этими таблицами? Перименовать в items и items_prototypes и раскидывать параметры между ними по мере необходимости?

Ну да. А если лень каждый раз тянуть прототипы, создай view.

**Comment by 3bl3gamer** [comment]
> Какие?

> же покрытие и максимальная прочночть могут поменяться после какой-нибудь модификации

**Comment by m1kc** [comment]
А проблема-то в чём? Ну поменяются, и что?

**Comment by 3bl3gamer** [comment]
Если они останутся в прототипах, то не смогут поменяться у какой-то одной конкретной шмотки.

**Comment by m1kc** [comment]
~~И нахуй так жить~~ И зачем это надо?

**Comment by 3bl3gamer** [comment]
поднять статы шмотки

> после какой-нибудь модификации

например

**Comment by m1kc** [comment]
Ну как будем их вводить - тогда и посмотрим. Пока так.

**Comment by m1kc** [comment]
Какие-то щиты как-то появились.

Материал, ценз и плюсы к статам не сделаны, потому что с ними ничего пока не понятно.

Удара щитом пока нет, это будет отдельная карточка.

Особой механики расчёта ударов щитом пока нет, это будет отдельная карточка.
