### ISSUE TITLE
setRevision не в том месте

### ISSUE THREAD

**Issue by m1kc** [uonline/uonline#537]
> Max Musatov, [01.07.15 19:26]
Ну Антон, ну бля, ну как так можно.
> 
Max Musatov, [01.07.15 19:28]
Почему setRevision вызывается не после того, как миграция выполнена, а после того, как выполнены все?

**Comment by 3bl3gamer** [comment]
Сами миграции работают, тесты оных проходят, проблема вроде как пофикшена... НО!
Эта `migrateOne` (которая применяется только в тестах для тестирования себя) упорно валит последний свой тест с
```
F....
>> migrateOne - errors
>> error: current transaction is aborted, commands ignored until end of transaction block
>>   at [object Object].Connection.parseE (node_modules/any-db-postgres/node_modules/pg/lib/connection.js:534:11)
>>   at [object Object].Connection.parseMessage (node_modules/any-db-postgres/node_modules/pg/lib/connection.js:361:17)
>>   at Socket.<anonymous> (node_modules/any-db-postgres/node_modules/pg/lib/connection.js:105:22)
>>   at Socket.emit (events.js:107:17)
>>   at readableAddChunk (_stream_readable.js:163:16)
>>   at Socket.Readable.push (_stream_readable.js:126:10)
>>   at TCP.onread (net.js:538:20)
```
, хотя там как-бе стоит `test.throws`, да и вообще в ту транзакцию никто два раза не стучится.

~~ох как же меня задолбали эти кривые стектрейсы с кривыми коллбеками из неведомых источников~~

**Comment by 3bl3gamer** [comment]
~~Да ё~~
Минус функция, плюс тесты https://github.com/uonline/uonline/commit/f2647d31955b9a5f3459a5e990c9222add3a5ed3
Бага в своей ветке.

**Comment by m1kc** [comment]
Найс.
