### ISSUE TITLE
Оружие и его экипировка

### ISSUE THREAD

**Issue by FaceLess1** [uonline/uonline#555]
**задача 1** 
""внести оружие на сервер и реализовать их помещение в инвентарь и экипировку"" 

у оружия есть собственные параметры повреждения, которые являются статическими.

в бою на количество влияет также сила персонажа. нанесенный урон рассчитывается по формуле:

(параметр силы персонажа + параметр урона от оружия - параметр защиты персонажа - параметр защиты от доспеха)/2 = средний нанесенный урон.

диапазон вероятно наносимого урона исходит из формулы урона, а именно:
0.8 * средний нанесенный урон -- 1.2 * средний нанесенный урон.

из представленного диапазона рандомно берется значение, которое реально соответствует конкретному удару.

**Comment by 3bl3gamer** [comment]
Ага. А что с прочностью? Уменьшение при ударах там и т.д. Или пока не надо?

**Comment by FaceLess1** [comment]
@3bl3gamer речи о прочности пока нет. я колеблюсь на этот счет.

**Comment by 3bl3gamer** [comment]
Текс.

Первый коммит: появился меч. Принцип работы как у щита, только без блокировани урона. И вообще теперь можно (теоретически) ударить любым предметом, у которого урон в параметрах больше нуля.

Второй коммит: исправил тип меча ("одноручное оружее" вместо "меч"), т.к. в https://github.com/uonline/universe/issues/62 описано подобное разделение по типам.
Удар за ход всегда один.
@m1kc, а зачем [тут](https://github.com/uonline/uonline/commit/82e7fd0509628a6b9ed169f731d4398fad1f1cb1#diff-4101d979f7d0a8de11c1d650006e3381L5) предметы выводились через проход по всему массив с проверкой типа? Вроде надеваемые предметы надеваются по одной штуке каждого типа.

Если экипировано оружее, кнопка меняется соответствующе:
![image](https://cloud.githubusercontent.com/assets/1857617/8820879/d0f6d454-3061-11e5-8baf-ee7952c4fcde.png)

**Comment by m1kc** [comment]
> а зачем тут предметы выводились через проход по всему массив с проверкой типа? Вроде надеваемые предметы надеваются по одной штуке каждого типа.

Нет. Амулетов может быть три, например. Верни как было.

**Comment by 3bl3gamer** [comment]
Вернул.

**Comment by FaceLess1** [comment]
задача 2:
реализовать разделение оружия на классы: 1) короткое, 2) одноручное, 3) двуручное, 4) цепное, 5) сверхтяжелое

практическая польза от реализации: 
1) просчитывается различное количество ударов, осуществляемых персонажем за ход -> для каждого удара своя вероятность попадания -> различный урон.
2) регистрируется количество опыта,(или что мы возьмем за основу показателя "Мастерства"?) полученного с тем или иным оружием -> навык мастерства повышается (но конкретно "Мастерство" не для этой задачи)
3) при экипировке двуручного, цепного (образцов которого у нас еще нет) и сверхтяжелого (также образцов нет) игрок теряет возможность носить второе оружие в руке или щиты -> прямое влияние на экипировку.

**Comment by m1kc** [comment]
\>> #565
