### ISSUE TITLE
Дифференциальная экипировка

### ISSUE THREAD

**Issue by FaceLess1** [uonline/uonline#558]
некоторое время тому назад мной высказывалась идея о том, что экипировка наплечников (область "Плечи"), наручей (область "Предплечья"), поножей (область "Голени") может быть различной. 
то есть на левой ноге я могу носить *условно* кожаную часть, а на правой -- металлическую, на правой руке усиленный кожаный наруч, а на левой вовсе не носить.
в связи с этим есть предложение слоты разделить на "правая часть" и "левая часть".

**Comment by FaceLess1** [comment]
**ВАЖНО**
орки не носят нагрудники и кирасы в качестве защиты. как следствие: они НИКОГДА не будут иметь 100% покрытия тела броней. взамен этого их броня крепче (прочнее), они от природы сильнее и могут носить вместо трех сумок с инвентарем сразу 4.

**Comment by FaceLess1** [comment]
**ВАЖНО**
я опять допустил ошибку и не заметил ранее: в слоте "Руки" предусматриваются перчатки или кольца? потому что должно быть и то, и другое.

**Comment by m1kc** [comment]
@FaceLess1 Да оперный театр. Когда мы раскидывали слоты, ты ничего не сказал про кольца.

**Comment by m1kc** [comment]
Кольца добавил. С нагрудниками разобрался. Решай, будем ли делить наплечники и прочее.

**Comment by m1kc** [comment]
@m1kc .

> я склоняюсь к мнению, что наплечники и наручи давай разделим на "правый" и "левый", а поножи, то есть то, что защищает голень, — идут комплектом.

**Comment by m1kc** [comment]
\>> #542
