### ISSUE TITLE
Виды оружия

### ISSUE THREAD

**Issue by FaceLess1** [uonline/uonline#573]
необходимо запилить разделение оружия по видам согласно таблице
![image](https://cloud.githubusercontent.com/assets/4042329/9980171/13337f16-5f97-11e5-8acc-97c27ecbee4f.png)

**Comment by m1kc** [comment]
bow, sword, mace, axe, staff, sphere, dagger, scythe, spear, hammer

**Comment by m1kc** [comment]
Готово. Жду следующей задачи.
