### ISSUE TITLE
Поправить виды оружия

### ISSUE THREAD

**Issue by m1kc** [uonline/uonline#581]
Сейчас там везде тупо sword.

```coffee
# id, name, type, class, kind, strength, coverage, damage
		[ 1, 'Железный шлем драконопоклонника', 'hat', null, null, 280, 10, null ]
		[ 2, 'Стальной шлем драконопоклонника', 'hat', null, null, 340, 10, null ]
		[ 3, 'Закрытый стальной шлем', 'hat', null, null, 500, 13, null ]
		[ 4, 'Стальной гладиаторский шлем', 'hat', null, null, 505, 13, null ]
		[ 5, 'Гладиаторский шлем из дюрали', 'hat', null, null, 580, 13, null ]
		[ 6, 'Железный топхелм', 'hat', null, null, 320, 12, null ]
		[ 7, 'Простой рогатый шлем', 'hat', null, null, 200, 6, null ]
		[ 8, 'Шипованный правый наплечник', 'pouldron-right', null, null, 480, 8, null ]
		[ 27, 'Железный правый наплечник', 'pouldron-right', null, null, 300, 10, null ]
		[ 9, 'Кожаные сапоги хуманов', 'boots', null, null, 100, 10, null ]
		[ 10, 'Кожаные сапоги урук-хаев', 'boots', null, null, 100, 10, null ]
		[ 11, 'Кожаные сапоги эльфов', 'boots', null, null, 100, 10, null ]
		[ 12, 'Укреплённый деревянный щит', 'shield', null, null, 440, 34, null ]
		[ 13, 'Короткий эльфийский меч', 'weapon-one-handed', 'normal', 'sword', 500, null, 70 ]
		[ 14, 'Стандартный эльфийский меч', 'weapon-one-handed', 'normal', 'sword', 750, null, 105 ]
		[ 15, 'Прямой стандартный эльфийский клинок', 'weapon-one-handed', 'normal', 'sword', 550, null, 90 ]
		[ 16, 'Zweihander', 'weapon-two-handed', 'normal', 'sword', 1750, null, 190 ]
		[ 17, 'Тяжелый тесак', 'weapon-one-handed', 'short', 'sword', 450, null, 80 ]
		[ 18, 'Шипованная дубина', 'weapon-one-handed', 'normal', 'sword', 350, null, 90 ]
		[ 19, 'Посох шамана', 'weapon-two-handed', 'normal', 'sword', 350, null, 35 ]
		[ 20, 'Деревянный посох', 'weapon-two-handed', 'normal', 'sword', 300, null, 25 ]
		[ 21, 'Усиленный меч', 'weapon-one-handed', 'normal', 'sword', 475, null, 75 ]
		[ 22, 'Стальной меч странника', 'weapon-one-handed', 'normal', 'sword', 505, null, 70 ]
		[ 23, 'Деревянная дубина', 'weapon-two-handed', 'normal', 'sword', 200, null, 105 ]
		[ 24, 'Простой железный меч', 'weapon-one-handed', 'normal', 'sword', 305, null, 65 ]
		[ 25, 'Коготь смерти', 'weapon-one-handed', 'normal', 'sword', 705, null, 140 ]
		[ 26, 'Тесак', 'weapon-one-handed', 'short', 'sword', 205, null, 45 ]

**Comment by m1kc** [comment]
В тред призывается @FaceLess1.

**Comment by m1kc** [comment]
```html
Класс:
							<select ng-model="item.class">
								<option value="normal">Обычное</option>
								<option value="short">Короткое</option>
								<option value="heavy">Сверхтяжёлое</option>
								<option value="chained">Цепное</option>
Вид:
							<select ng-model="item.kind" ng-value="normal">
								<option value="bow">Лук</option>
								<option value="sword">Меч</option>
								<option value="mace">Булава или дубина</option>
								<option value="axe">Топор или секира</option>
								<option value="staff">Магический посох</option>
								<option value="sphere">Магическая сфера</option>
								<option value="dagger">Кинжал или нож</option>
								<option value="scythe">Коса</option>
								<option value="spear">Копьё, алебарда, пика или боевой посох</option>
								<option value="hammer">Молот</option>

**Comment by FaceLess1** [comment]
# id, name, type, class, kind, strength, coverage, damage
        [ 1, 'Железный шлем драконопоклонника', 'hat', null, null, 280, 10, null ]
        [ 2, 'Стальной шлем драконопоклонника', 'hat', null, null, 340, 10, null ]
        [ 3, 'Закрытый стальной шлем', 'hat', null, null, 500, 13, null ]
        [ 4, 'Стальной гладиаторский шлем', 'hat', null, null, 505, 13, null ]
        [ 5, 'Гладиаторский шлем из дюрали', 'hat', null, null, 580, 13, null ]
        [ 6, 'Железный топхелм', 'hat', null, null, 320, 12, null ]
        [ 7, 'Простой рогатый шлем', 'hat', null, null, 200, 6, null ]
        [ 8, 'Шипованный правый наплечник', 'pouldron-right', null, null, 480, 8, null ]
        [ 27, 'Железный правый наплечник', 'pouldron-right', null, null, 300, 10, null ]
        [ 9, 'Кожаные сапоги хуманов', 'boots', null, null, 100, 10, null ]
        [ 10, 'Кожаные сапоги урук-хаев', 'boots', null, null, 100, 10, null ]
        [ 11, 'Кожаные сапоги эльфов', 'boots', null, null, 100, 10, null ]
        [ 12, 'Укреплённый деревянный щит', 'shield', null, null, 440, 34, null ]
        [ 13, 'Короткий эльфийский меч', 'weapon-one-handed', 'normal', 'sword', 500, null, 70 ]
        [ 14, 'Стандартный эльфийский меч', 'weapon-one-handed', 'normal', 'sword', 750, null, 105 ]
        [ 15, 'Прямой стандартный эльфийский клинок', 'weapon-one-handed', 'normal', 'sword', 550, null, 90 ]
        [ 16, 'Zweihander', 'weapon-two-handed', 'normal', 'sword', 1750, null, 190 ]
        [ 17, 'Тяжелый тесак', 'weapon-one-handed', 'short', 'dagger', 450, null, 80 ]
        [ 18, 'Шипованная дубина', 'weapon-one-handed', 'normal', 'mace', 350, null, 90 ]
        [ 19, 'Посох шамана', 'weapon-two-handed', 'normal', 'staff', 350, null, 35 ]
        [ 20, 'Деревянный посох', 'weapon-two-handed', 'normal', 'staff', 300, null, 25 ]
        [ 21, 'Усиленный меч', 'weapon-one-handed', 'normal', 'sword', 475, null, 75 ]
        [ 22, 'Стальной меч странника', 'weapon-one-handed', 'normal', 'sword', 505, null, 70 ]
        [ 23, 'Деревянная дубина', 'weapon-two-handed', 'normal', 'mace', 200, null, 105 ]
        [ 24, 'Простой железный меч', 'weapon-one-handed', 'normal', 'sword', 305, null, 65 ]
        [ 25, 'Коготь смерти', 'weapon-one-handed', 'normal', 'sword', 705, null, 140 ]
        [ 26, 'Тесак', 'weapon-one-handed', 'short', 'sword', 205, null, 45 ]
