### ISSUE TITLE
Броня по видам

### ISSUE THREAD

**Issue by FaceLess1** [uonline/uonline#582]
Вся броня делится на:
- тряпичную
- легкую кожаную
- кожаную
- костяную
- кольчужную
- пластинчатую
- легкую латную
- латную
- тяжелую латную

в общем, надо запилить такое разделение.

**Comment by m1kc** [comment]
* cloth
* light leather
* leather
* bone
* mail
* plate
* light cuirass
* cuirass
* heavy cuirass

**Comment by m1kc** [comment]
Готово. Жду исправленных предметов и следующей задачи.
