### ISSUE TITLE
Grunt -> Gulp

### ISSUE THREAD

**Issue by m1kc** [uonline/uonline#597]
Осталось:

* [x] coffee-jshint
* [x] mustcontain
* [x] ~~codo~~
* [x] default task
* [x] Обновить Readme

Опционально:

* Параллельный check? Кастомные репортеры? Особенно coffeelint, этот совсем уёбищный.
* `gulp default --help`?
* Sourcemaps?
* Аналог nodemon?
* [x] Слить check в одну большую трубу с фильтрами? Как это повлияет на скорость?

**Comment by m1kc** [comment]
* LiveReload? Это вообще возможно при такой архитектуре? А как сделать так, чтобы было возможно?
* Stylus отдельным файлом?

**Comment by 3bl3gamer** [comment]
> вообще возможно
Повесить `nodemon`'у на изменение `brwser.json` действия из `gulp.task build`?
Но мне это всё равно не нравится, потому что непонятно, нажал ли я в браузере Ф5 до того, как `build` отработал или после.

**Comment by m1kc** [comment]
Так в этом и фишка LiveReload - он F5 за тебя нажимает. http://livereload.com/

**Comment by m1kc** [comment]
Done.
