### ISSUE TITLE
Зависимость экспы с монстров от баланса уровней

### ISSUE THREAD

**Issue by FaceLess1** [uonline/uonline#601]
`(1+(Lm-Lp)*0,1)*50` = `50+5*(Lm-Lp)`,

где Lm - уровень монстра, Lp - уровень игрока

**Comment by 3bl3gamer** [comment]
Забыл поставить ссылку сюда https://github.com/uonline/uonline/commit/00941b0185a045472097659e6a922fd0b72aaa4c

**Comment by m1kc** [comment]
@FaceLess1 Ну тут вроде всё, жду следующей задачи.
